import React, { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { 
  Upload, 
  FileSearch, 
  BarChart, 
  ShieldCheck, 
  AlertOctagon, 
  Download,
  Share2,
  Trash2,
  Play,
  Maximize2,
  AlertTriangle
} from 'lucide-react';
import { cn } from '@/src/lib/utils';
import { analyzeMedia, ForensicResult, runFollowUpChat } from '../services/aiService';
import { db, auth } from '../lib/firebase';
import { collection, addDoc, serverTimestamp } from 'firebase/firestore';
import { MessageSquare, Send, Bot } from 'lucide-react';

export function Forensics() {
  const [file, setFile] = useState<File | null>(null);
  const [preview, setPreview] = useState<string | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<ForensicResult | null>(null);
  const [chatHistory, setChatHistory] = useState<{ role: "user" | "model"; parts: { text: string }[] }[]>([]);
  const [userMessage, setUserMessage] = useState("");
  const [isChatting, setIsChatting] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const chatEndRef = useRef<HTMLDivElement>(null);

  const resetForensics = () => {
    setFile(null);
    setPreview(null);
    setResult(null);
    setChatHistory([]);
    setUserMessage("");
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selected = e.target.files?.[0];
    if (selected) {
      setFile(selected);
      const reader = new FileReader();
      reader.onloadend = () => setPreview(reader.result as string);
      reader.readAsDataURL(selected);
      setResult(null);
      setChatHistory([]);
    }
  };

  const startAnalysis = async () => {
    if (!file || !preview) return;
    setIsAnalyzing(true);
    try {
      const base64Data = preview.split(',')[1];
      const type = file.type.split('/')[0] as "image" | "video" | "audio";
      const analysisResult = await analyzeMedia(base64Data, file.type, type);
      setResult(analysisResult);
      setChatHistory([
        { role: "user", parts: [{ text: "Analyze this media." }] },
        { role: "model", parts: [{ text: `Analysis complete. Verdict: ${analysisResult.verdict}. Summary: ${analysisResult.summary}` }] }
      ]);

      // Save to Firestore if user is logged in
      if (auth.currentUser) {
        await addDoc(collection(db, 'investigations'), {
          fileName: file.name,
          fileType: type,
          status: 'completed',
          trustScore: analysisResult.trustScore,
          verdict: analysisResult.verdict,
          summary: analysisResult.summary,
          ownerId: auth.currentUser.uid,
          createdAt: serverTimestamp(),
          isPublic: false
        });
      }
    } catch (error) {
      console.error("Analysis failed:", error);
      alert("Cyber-Forensics system offline or analysis failed.");
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleSendMessage = async () => {
    if (!userMessage.trim() || !preview || isChatting) return;
    
    const newMessage = { role: "user" as const, parts: [{ text: userMessage }] };
    const updatedHistory = [...chatHistory, newMessage];
    setChatHistory(updatedHistory);
    setUserMessage("");
    setIsChatting(true);

    try {
      const base64Data = preview.split(',')[1];
      const response = await runFollowUpChat(updatedHistory, userMessage, base64Data, file?.type);
      setChatHistory([...updatedHistory, { role: "model", parts: [{ text: response }] }]);
      setTimeout(() => chatEndRef.current?.scrollIntoView({ behavior: 'smooth' }), 100);
    } catch (error) {
      console.error("Chat failed:", error);
    } finally {
      setIsChatting(false);
    }
  };

  const exportReport = () => {
    if (!result) return;
    const report = `
DEEPFAKE SHIELD AI - FORENSIC REPORT
====================================
CASE ID: ${Math.random().toString(36).substring(7).toUpperCase()}
FILE: ${file?.name}
VERDICT: ${result.verdict}
TRUST SCORE: ${result.trustScore}/100

EXECUTIVE SUMMARY:
${result.summary}

DETAILED EXPLANATION:
${result.explanation}

ARTIFACTS DETECTED:
${result.artifacts.map(a => `- [${a.type}] ${a.description} (Confidence: ${a.confidence})`).join('\n')}

GENERATED BY SHIELD AI UNIT-07
TIMESTAMP: ${new Date().toISOString()}
    `;
    const blob = new Blob([report], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `ShieldAI_Report_${file?.name}.txt`;
    link.click();
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-700">
      <section className="flex flex-col md:flex-row justify-between items-start md:items-end gap-4 border-b border-white/5 pb-8">
        <div>
          <div className="flex items-center gap-2 text-cyber-lime mb-2">
            <FileSearch className="w-4 h-4" />
            <span className="font-mono text-[10px] uppercase tracking-widest font-bold">Forensic Unit / Lab 04</span>
          </div>
          <h1 className="text-4xl font-bold tracking-tighter text-white">MEDIA AUTHENTICATION</h1>
        </div>
        <div className="flex gap-3">
          {(file || result) && (
            <button 
              onClick={resetForensics}
              className="px-4 py-2 bg-cyber-lime/10 border border-cyber-lime/30 text-cyber-lime rounded text-xs font-mono font-bold hover:bg-cyber-lime/20 transition-all uppercase tracking-tighter"
            >
              NEW_SCAN
            </button>
          )}
          <button 
            onClick={exportReport}
            className="px-4 py-2 glass-panel text-xs font-mono font-bold hover:bg-white/5 transition-colors disabled:opacity-50"
            disabled={!result}
          >
            EXPORT_REPORT
          </button>
          <button className="px-4 py-2 bg-red-500 text-cyber-navy rounded text-xs font-mono font-bold flex items-center gap-2">
            <AlertOctagon className="w-4 h-4" />
            FLAG_AS_FRAUD
          </button>
        </div>
      </section>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        {/* Upload & Preview */}
        <div className={cn(
          "transition-all duration-500",
          result ? "lg:col-span-8" : "lg:col-span-12"
        )}>
          {!preview ? (
            <div 
              onClick={() => fileInputRef.current?.click()}
              className="group aspect-video w-full glass-panel border-dashed border-2 border-white/10 rounded-2xl flex flex-col items-center justify-center cursor-pointer hover:border-cyber-lime/40 transition-all hover:bg-cyber-lime/[0.02]"
            >
              <div className="w-16 h-16 rounded-full bg-white/5 flex items-center justify-center mb-6 group-hover:scale-110 group-hover:bg-cyber-lime/10 transition-all">
                <Upload className="w-8 h-8 text-white/40 group-hover:text-cyber-lime" />
              </div>
              <p className="text-lg font-medium text-white/60 mb-2">Drag Forensic Asset to Terminal</p>
              <p className="text-xs font-mono text-white/20 uppercase tracking-widest">Supports Image, Video, Audio (MAX 50MB)</p>
              <input 
                ref={fileInputRef}
                type="file" 
                className="hidden" 
                onChange={handleFileChange}
                accept="image/*,video/*,audio/*"
              />
            </div>
          ) : (
            <div className="relative group">
              <div className="aspect-video w-full rounded-2xl overflow-hidden glass-panel flex items-center justify-center bg-black/40 border border-white/10">
                {file?.type.startsWith('image/') && (
                  <img src={preview} alt="Forensic Target" className="w-full h-full object-contain opacity-80" />
                )}
                {file?.type.startsWith('video/') && (
                  <video src={preview} controls className="w-full h-full object-contain opacity-80" />
                )}
                {file?.type.startsWith('audio/') && (
                  <div className="flex flex-col items-center gap-6">
                    <div className="flex items-center gap-1">
                      {[...Array(12)].map((_, i) => (
                        <div key={i} className="w-1.5 h-12 bg-cyber-lime/40 rounded-full animate-pulse" style={{ animationDelay: `${i*100}ms` }} />
                      ))}
                    </div>
                    <audio src={preview} controls className="w-64" />
                  </div>
                )}

                {/* Tactical HUD Overlay for Preview */}
                <div className="absolute inset-0 pointer-events-none p-6 flex flex-col justify-between">
                  <div className="flex justify-between items-start">
                    <div className="bg-cyber-navy/80 backdrop-blur-md border border-white/10 px-3 py-1.5 rounded-full flex items-center gap-2">
                       <div className="w-2 h-2 rounded-full bg-cyber-lime animate-pulse" />
                       <span className="text-[10px] font-mono text-cyber-lime uppercase font-bold tracking-widest">LIVE_SENSORS</span>
                    </div>
                    <div className="text-right">
                       <p className="text-[10px] font-mono text-white/40 mb-1">ZOOM: {result ? 'AUTO_FIT' : '1.0X'}</p>
                       <p className="text-[10px] font-mono text-white/40">RESOLUTION: {file?.size ? (file.size / 1024).toFixed(0) + ' KB' : 'N/A'}</p>
                    </div>
                  </div>

                  {result && (
                     <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-64 h-64 border border-cyber-lime/40 rounded-3xl animate-pulse">
                        <div className="absolute -top-1 -left-1 w-4 h-4 border-t-2 border-l-2 border-cyber-lime" />
                        <div className="absolute -top-1 -right-1 w-4 h-4 border-t-2 border-r-2 border-cyber-lime" />
                        <div className="absolute -bottom-1 -left-1 w-4 h-4 border-b-2 border-l-2 border-cyber-lime" />
                        <div className="absolute -bottom-1 -right-1 w-4 h-4 border-b-2 border-r-2 border-cyber-lime" />
                     </div>
                  )}

                  <div className="flex justify-between items-end">
                    <div className="space-y-1">
                       <p className="text-[10px] font-mono text-white/40">FILE: {file?.name.toUpperCase()}</p>
                       <p className="text-[10px] font-mono text-white/40">COORD: 42.12 // 09.43</p>
                    </div>
                    <div className="flex gap-4">
                       <button onClick={resetForensics} className="p-2 rounded bg-red-500/10 hover:bg-red-500/20 text-red-400 pointer-events-auto">
                          <Trash2 className="w-4 h-4" />
                       </button>
                    </div>
                  </div>
                </div>
              </div>
              
              {!result && !isAnalyzing && (
                <div className="mt-8 flex justify-center">
                  <button 
                  onClick={startAnalysis}
                  className="bg-cyber-lime text-cyber-navy px-12 py-4 rounded-xl font-bold font-mono tracking-widest uppercase hover:scale-105 active:scale-95 transition-all shadow-[0_0_30px_rgba(173,255,47,0.3)] flex items-center gap-3">
                    <FileSearch className="w-5 h-5" />
                    Initiate Forensic Analysis
                  </button>
                </div>
              )}
            </div>
          )}
        </div>

        {/* Results Sidebar */}
        <AnimatePresence>
          {(isAnalyzing || result) && (
            <motion.div 
              initial={{ opacity: 0, x: 20 }}
              animate={{ opacity: 1, x: 0 }}
              exit={{ opacity: 0, x: 20 }}
              className="lg:col-span-4 space-y-6"
            >
              {isAnalyzing ? (
                <div className="glass-panel p-8 h-full flex flex-col items-center justify-center gap-6 text-center">
                  <div className="w-24 h-24 relative">
                    <div className="absolute inset-0 border-4 border-white/5 rounded-full" />
                    <div className="absolute inset-0 border-4 border-cyber-lime border-t-transparent rounded-full animate-spin" />
                    <div className="absolute inset-4 bg-cyber-lime/10 rounded-full flex items-center justify-center">
                      <BarChart className="w-8 h-8 text-cyber-lime animate-pulse" />
                    </div>
                  </div>
                  <div className="space-y-2">
                    <h3 className="text-xl font-bold text-white tracking-tight">System Analyzing Assets</h3>
                    <p className="text-xs font-mono text-white/40 uppercase tracking-widest">Accessing Neural Forensic DB...</p>
                  </div>
                  <div className="w-48 h-1 bg-white/5 rounded-full overflow-hidden mt-4">
                    <motion.div 
                      className="h-full bg-cyber-lime"
                      animate={{ x: [-200, 200] }}
                      transition={{ duration: 1.5, repeat: Infinity, ease: "linear" }}
                    />
                  </div>
                </div>
              ) : result && (
                <>
                  {/* Trust Score Card */}
                  <div className="glass-panel p-6">
                    <div className="flex justify-between items-center mb-6">
                      <h3 className="text-[10px] font-mono font-bold text-white/40 uppercase tracking-widest">AUTHENTICITY_METRIC</h3>
                      <ShieldCheck className={cn("w-5 h-5", result.trustScore > 70 ? "text-cyber-lime" : "text-cyber-alert")} />
                    </div>
                    <div className="flex items-baseline gap-2 mb-4">
                      <span className={cn("text-6xl font-bold tracking-tighter", result.trustScore > 70 ? "text-cyber-lime" : "text-red-400 text-glow")}>{result.trustScore}</span>
                      <span className="text-lg font-mono text-white/20">/100</span>
                    </div>
                    <div className="w-full h-1.5 bg-white/5 rounded-full overflow-hidden mb-6">
                      <motion.div 
                        initial={{ width: 0 }}
                        animate={{ width: `${result.trustScore}%` }}
                        className={cn("h-full", result.trustScore > 70 ? "bg-cyber-lime" : "bg-red-400")} 
                      />
                    </div>
                    <div className="p-3 rounded bg-white/5 border border-white/10">
                       <p className="text-sm font-medium text-white mb-1 uppercase tracking-tight">{result.verdict}</p>
                       <p className="text-xs text-white/40 leading-relaxed italic">{result.summary}</p>
                    </div>
                  </div>

                  {/* AI Reasoning */}
                  <div className="glass-panel p-6 flex flex-col h-[500px]">
                    <div className="flex items-center justify-between mb-6 border-b border-white/5 pb-4">
                      <div className="flex items-center gap-2">
                        <div className="w-6 h-6 rounded-full bg-gradient-to-tr from-blue-500 to-purple-500 flex items-center justify-center">
                          <Bot className="w-3 h-3 text-white" />
                        </div>
                        <h3 className="text-[10px] font-mono font-bold text-white/40 uppercase tracking-widest">FORENSIC_ASSISTANT</h3>
                      </div>
                      <span className="text-[9px] font-bold text-cyber-lime/40 animate-pulse">TERMINAL_UP</span>
                    </div>

                    <div className="flex-1 overflow-y-auto space-y-4 mb-4 scrollbar-hide pr-2">
                      {chatHistory.slice(1).map((msg, i) => (
                        <div key={i} className={cn(
                          "max-w-[90%] p-3 rounded-lg text-xs",
                          msg.role === 'user' 
                            ? "bg-white/5 ml-auto border border-white/5 text-white/80" 
                            : "bg-cyber-navy mr-auto border border-cyber-lime/10 text-white/90"
                        )}>
                          <p className="leading-relaxed whitespace-pre-wrap">{msg.parts[0].text}</p>
                        </div>
                      ))}
                      {isChatting && (
                        <div className="bg-cyber-navy mr-auto border border-cyber-lime/10 p-3 rounded-lg flex gap-2 items-center text-xs text-white/40 italic">
                          <div className="flex gap-1">
                            <div className="w-1 h-1 bg-cyber-lime rounded-full animate-bounce" />
                            <div className="w-1 h-1 bg-cyber-lime rounded-full animate-bounce delay-100" />
                            <div className="w-1 h-1 bg-cyber-lime rounded-full animate-bounce delay-200" />
                          </div>
                          Unit analyzing forensic queries...
                        </div>
                      )}
                      <div ref={chatEndRef} />
                    </div>

                    <div className="flex gap-2 bg-black/20 p-2 rounded-lg border border-white/5">
                      <input 
                        type="text" 
                        value={userMessage}
                        onChange={(e) => setUserMessage(e.target.value)}
                        onKeyDown={(e) => e.key === 'Enter' && handleSendMessage()}
                        placeholder="ASK ABOUT FORENSIC MARKERS..."
                        className="flex-1 bg-transparent border-none focus:ring-0 text-[11px] font-mono placeholder:text-white/20"
                      />
                      <button 
                        onClick={handleSendMessage}
                        disabled={isChatting || !userMessage.trim()}
                        className="p-1.5 rounded bg-cyber-lime text-cyber-navy hover:scale-105 active:scale-95 transition-all disabled:opacity-50"
                      >
                        <Send className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>

                  {/* Artifacts Breakdown */}
                  <div className="glass-panel p-6">
                    <div className="flex items-center gap-2 mb-6 border-b border-white/5 pb-4">
                      <BarChart className="w-4 h-4 text-white/40" />
                      <h3 className="text-[10px] font-mono font-bold text-white/40 uppercase tracking-widest">DETECTED_ARTIFACTS</h3>
                    </div>
                    <div className="space-y-3">
                      {result.artifacts.map((art, i) => (
                        <div key={i} className="p-3 rounded bg-cyber-navy border border-white/5 flex items-start gap-3">
                           <div className="mt-1 w-1.5 h-1.5 rounded-full bg-cyber-lime" />
                           <div>
                              <p className="text-[11px] font-bold text-white uppercase mb-0.5">{art.type}</p>
                              <p className="text-[10px] text-white/40 leading-tight">{art.description}</p>
                           </div>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* Warning System */}
                  {result.trustScore < 50 && (
                    <motion.div 
                      initial={{ scale: 0.9, opacity: 0 }}
                      animate={{ scale: 1, opacity: 1 }}
                      className="p-5 rounded-xl bg-red-500/10 border border-red-500/30 relative overflow-hidden"
                    >
                      <div className="absolute -top-4 -right-4 opacity-10">
                        <AlertOctagon className="w-24 h-24 text-red-500" />
                      </div>
                      <h4 className="text-red-500 font-bold mb-2 flex items-center gap-2">
                         <AlertTriangle className="w-4 h-4" />
                         THINK BEFORE SHARING
                      </h4>
                      <p className="text-[11px] text-red-400/80 leading-relaxed uppercase font-mono tracking-tighter">
                         High risk detection: This media displays significant synthetic markers. Sharing without disclosure promotes misinformation.
                      </p>
                    </motion.div>
                  )}
                </>
              )}
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}
